/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as ControlRoomRouteImport } from './routes/control-room'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FulfilmentRouteImport } from './routes/fulfilment'
import { Route as KybRouteImport } from './routes/kyb'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OtpLookupRouteImport } from './routes/otp-lookup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as AuctionsIdRouteImport } from './routes/auctions.$id'
import { Route as AuctionsLiveRouteImport } from './routes/auctions.live'
import { Route as AuctionsNewRouteImport } from './routes/auctions.new'
import { Route as AuctionsPublishRouteImport } from './routes/auctions.publish'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as OrganizationsIdRouteImport } from './routes/organizations.$id'
import { Route as OrganizationsNewRouteImport } from './routes/organizations.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAuctionsRouteImport } from './routes/settings.auctions'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsKybRouteImport } from './routes/settings.kyb'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsOtpRouteImport } from './routes/settings.otp'
import { Route as SettingsPlatformRouteImport } from './routes/settings.platform'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as VendorsIdRouteImport } from './routes/vendors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoomRoute = ControlRoomRouteImport.update({
  id: '/control-room',
  path: '/control-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FulfilmentRoute = FulfilmentRouteImport.update({
  id: '/fulfilment',
  path: '/fulfilment',
  getParentRoute: () => rootRouteImport,
} as any)
const KybRoute = KybRouteImport.update({
  id: '/kyb',
  path: '/kyb',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpLookupRoute = OtpLookupRouteImport.update({
  id: '/otp-lookup',
  path: '/otp-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuctionsLiveRoute = AuctionsLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuctionsNewRoute = AuctionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuctionsPublishRoute = AuctionsPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AuctionsRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdRoute = OrganizationsIdRouteImport.update({
  id: '/organizations/$id',
  path: '/organizations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuctionsRoute = SettingsAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKybRoute = SettingsKybRouteImport.update({
  id: '/kyb',
  path: '/kyb',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOtpRoute = SettingsOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPlatformRoute = SettingsPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdRoute = VendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/audit-log': typeof AuditLogRoute
  '/categories': typeof CategoriesRoute
  '/compliance': typeof ComplianceRoute
  '/configuration': typeof ConfigurationRoute
  '/control-room': typeof ControlRoomRoute
  '/exceptions': typeof ExceptionsRoute
  '/finance': typeof FinanceRoute
  '/fulfilment': typeof FulfilmentRoute
  '/kyb': typeof KybRoute
  '/login': typeof LoginRoute
  '/otp-lookup': typeof OtpLookupRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/tokens': typeof TokensRoute
  '/users': typeof UsersRouteWithChildren
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/live': typeof AuctionsLiveRoute
  '/auctions/new': typeof AuctionsNewRoute
  '/auctions/publish': typeof AuctionsPublishRoute
  '/customers/$id': typeof CustomersIdRoute
  '/events/$id': typeof EventsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings/auctions': typeof SettingsAuctionsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/kyb': typeof SettingsKybRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/otp': typeof SettingsOtpRoute
  '/settings/platform': typeof SettingsPlatformRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/users/new': typeof UsersNewRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/categories': typeof CategoriesRoute
  '/compliance': typeof ComplianceRoute
  '/configuration': typeof ConfigurationRoute
  '/control-room': typeof ControlRoomRoute
  '/exceptions': typeof ExceptionsRoute
  '/finance': typeof FinanceRoute
  '/fulfilment': typeof FulfilmentRoute
  '/kyb': typeof KybRoute
  '/login': typeof LoginRoute
  '/otp-lookup': typeof OtpLookupRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/templates': typeof TemplatesRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/tokens': typeof TokensRoute
  '/users': typeof UsersRouteWithChildren
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/live': typeof AuctionsLiveRoute
  '/auctions/new': typeof AuctionsNewRoute
  '/auctions/publish': typeof AuctionsPublishRoute
  '/customers/$id': typeof CustomersIdRoute
  '/events/$id': typeof EventsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings/auctions': typeof SettingsAuctionsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/kyb': typeof SettingsKybRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/otp': typeof SettingsOtpRoute
  '/settings/platform': typeof SettingsPlatformRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/users/new': typeof UsersNewRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/auctions': typeof AuctionsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/events': typeof EventsIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/audit-log': typeof AuditLogRoute
  '/categories': typeof CategoriesRoute
  '/compliance': typeof ComplianceRoute
  '/configuration': typeof ConfigurationRoute
  '/control-room': typeof ControlRoomRoute
  '/exceptions': typeof ExceptionsRoute
  '/finance': typeof FinanceRoute
  '/fulfilment': typeof FulfilmentRoute
  '/kyb': typeof KybRoute
  '/login': typeof LoginRoute
  '/otp-lookup': typeof OtpLookupRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/tokens': typeof TokensRoute
  '/users': typeof UsersRouteWithChildren
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/live': typeof AuctionsLiveRoute
  '/auctions/new': typeof AuctionsNewRoute
  '/auctions/publish': typeof AuctionsPublishRoute
  '/customers/$id': typeof CustomersIdRoute
  '/events/$id': typeof EventsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings/auctions': typeof SettingsAuctionsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/kyb': typeof SettingsKybRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/otp': typeof SettingsOtpRoute
  '/settings/platform': typeof SettingsPlatformRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/users/new': typeof UsersNewRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/auctions'
    | '/audit-log'
    | '/categories'
    | '/compliance'
    | '/configuration'
    | '/control-room'
    | '/exceptions'
    | '/finance'
    | '/fulfilment'
    | '/kyb'
    | '/login'
    | '/otp-lookup'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/templates'
    | '/terms-conditions'
    | '/tokens'
    | '/users'
    | '/auctions/$id'
    | '/auctions/live'
    | '/auctions/new'
    | '/auctions/publish'
    | '/customers/$id'
    | '/events/$id'
    | '/organizations/$id'
    | '/organizations/new'
    | '/settings/auctions'
    | '/settings/integrations'
    | '/settings/kyb'
    | '/settings/notifications'
    | '/settings/otp'
    | '/settings/platform'
    | '/settings/security'
    | '/users/new'
    | '/vendors/$id'
    | '/auctions/'
    | '/customers/'
    | '/events/'
    | '/organizations/'
    | '/settings/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit-log'
    | '/categories'
    | '/compliance'
    | '/configuration'
    | '/control-room'
    | '/exceptions'
    | '/finance'
    | '/fulfilment'
    | '/kyb'
    | '/login'
    | '/otp-lookup'
    | '/reports'
    | '/risk'
    | '/templates'
    | '/terms-conditions'
    | '/tokens'
    | '/users'
    | '/auctions/$id'
    | '/auctions/live'
    | '/auctions/new'
    | '/auctions/publish'
    | '/customers/$id'
    | '/events/$id'
    | '/organizations/$id'
    | '/organizations/new'
    | '/settings/auctions'
    | '/settings/integrations'
    | '/settings/kyb'
    | '/settings/notifications'
    | '/settings/otp'
    | '/settings/platform'
    | '/settings/security'
    | '/users/new'
    | '/vendors/$id'
    | '/auctions'
    | '/customers'
    | '/events'
    | '/organizations'
    | '/settings'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/auctions'
    | '/audit-log'
    | '/categories'
    | '/compliance'
    | '/configuration'
    | '/control-room'
    | '/exceptions'
    | '/finance'
    | '/fulfilment'
    | '/kyb'
    | '/login'
    | '/otp-lookup'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/templates'
    | '/terms-conditions'
    | '/tokens'
    | '/users'
    | '/auctions/$id'
    | '/auctions/live'
    | '/auctions/new'
    | '/auctions/publish'
    | '/customers/$id'
    | '/events/$id'
    | '/organizations/$id'
    | '/organizations/new'
    | '/settings/auctions'
    | '/settings/integrations'
    | '/settings/kyb'
    | '/settings/notifications'
    | '/settings/otp'
    | '/settings/platform'
    | '/settings/security'
    | '/users/new'
    | '/vendors/$id'
    | '/auctions/'
    | '/customers/'
    | '/events/'
    | '/organizations/'
    | '/settings/'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuctionsRoute: typeof AuctionsRouteWithChildren
  AuditLogRoute: typeof AuditLogRoute
  CategoriesRoute: typeof CategoriesRoute
  ComplianceRoute: typeof ComplianceRoute
  ConfigurationRoute: typeof ConfigurationRoute
  ControlRoomRoute: typeof ControlRoomRoute
  ExceptionsRoute: typeof ExceptionsRoute
  FinanceRoute: typeof FinanceRoute
  FulfilmentRoute: typeof FulfilmentRoute
  KybRoute: typeof KybRoute
  LoginRoute: typeof LoginRoute
  OtpLookupRoute: typeof OtpLookupRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  TokensRoute: typeof TokensRoute
  UsersRoute: typeof UsersRouteWithChildren
  CustomersIdRoute: typeof CustomersIdRoute
  EventsIdRoute: typeof EventsIdRoute
  OrganizationsIdRoute: typeof OrganizationsIdRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  VendorsIdRoute: typeof VendorsIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-room': {
      id: '/control-room'
      path: '/control-room'
      fullPath: '/control-room'
      preLoaderRoute: typeof ControlRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfilment': {
      id: '/fulfilment'
      path: '/fulfilment'
      fullPath: '/fulfilment'
      preLoaderRoute: typeof FulfilmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyb': {
      id: '/kyb'
      path: '/kyb'
      fullPath: '/kyb'
      preLoaderRoute: typeof KybRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp-lookup': {
      id: '/otp-lookup'
      path: '/otp-lookup'
      fullPath: '/otp-lookup'
      preLoaderRoute: typeof OtpLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auctions/live': {
      id: '/auctions/live'
      path: '/live'
      fullPath: '/auctions/live'
      preLoaderRoute: typeof AuctionsLiveRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auctions/new': {
      id: '/auctions/new'
      path: '/new'
      fullPath: '/auctions/new'
      preLoaderRoute: typeof AuctionsNewRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auctions/publish': {
      id: '/auctions/publish'
      path: '/publish'
      fullPath: '/auctions/publish'
      preLoaderRoute: typeof AuctionsPublishRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/auctions': {
      id: '/settings/auctions'
      path: '/auctions'
      fullPath: '/settings/auctions'
      preLoaderRoute: typeof SettingsAuctionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/kyb': {
      id: '/settings/kyb'
      path: '/kyb'
      fullPath: '/settings/kyb'
      preLoaderRoute: typeof SettingsKybRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/otp': {
      id: '/settings/otp'
      path: '/otp'
      fullPath: '/settings/otp'
      preLoaderRoute: typeof SettingsOtpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/platform': {
      id: '/settings/platform'
      path: '/platform'
      fullPath: '/settings/platform'
      preLoaderRoute: typeof SettingsPlatformRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof UsersRoute
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id': {
      id: '/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof VendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuctionsRouteChildren {
  AuctionsIdRoute: typeof AuctionsIdRoute
  AuctionsLiveRoute: typeof AuctionsLiveRoute
  AuctionsNewRoute: typeof AuctionsNewRoute
  AuctionsPublishRoute: typeof AuctionsPublishRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

const AuctionsRouteChildren: AuctionsRouteChildren = {
  AuctionsIdRoute: AuctionsIdRoute,
  AuctionsLiveRoute: AuctionsLiveRoute,
  AuctionsNewRoute: AuctionsNewRoute,
  AuctionsPublishRoute: AuctionsPublishRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
}

const AuctionsRouteWithChildren = AuctionsRoute._addFileChildren(
  AuctionsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAuctionsRoute: typeof SettingsAuctionsRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsKybRoute: typeof SettingsKybRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsOtpRoute: typeof SettingsOtpRoute
  SettingsPlatformRoute: typeof SettingsPlatformRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAuctionsRoute: SettingsAuctionsRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsKybRoute: SettingsKybRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsOtpRoute: SettingsOtpRoute,
  SettingsPlatformRoute: SettingsPlatformRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface UsersRouteChildren {
  UsersNewRoute: typeof UsersNewRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersNewRoute: UsersNewRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuctionsRoute: AuctionsRouteWithChildren,
  AuditLogRoute: AuditLogRoute,
  CategoriesRoute: CategoriesRoute,
  ComplianceRoute: ComplianceRoute,
  ConfigurationRoute: ConfigurationRoute,
  ControlRoomRoute: ControlRoomRoute,
  ExceptionsRoute: ExceptionsRoute,
  FinanceRoute: FinanceRoute,
  FulfilmentRoute: FulfilmentRoute,
  KybRoute: KybRoute,
  LoginRoute: LoginRoute,
  OtpLookupRoute: OtpLookupRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  TokensRoute: TokensRoute,
  UsersRoute: UsersRouteWithChildren,
  CustomersIdRoute: CustomersIdRoute,
  EventsIdRoute: EventsIdRoute,
  OrganizationsIdRoute: OrganizationsIdRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  VendorsIdRoute: VendorsIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
